In [1]:
import pandas as pd

In [2]:
pd.__version__

'3.0.2'

In [ ]:
#1. Create DataFrame
df = pd.DataFrame([11,22,33],columns=['col_Name'])
print(df)

   col_Name
0        14
1        18
2         2

In [6]:
print(type(df))

<class 'pandas.DataFrame'>

In [ ]:
data = {
    'Name' : ['Rawal', 'Mahesh', 'Yogita','Dhawal'],
    'Age' : [38,21,11,20],
    'Salary' : [10000,20000,30000,40000]
}

In [8]:
df = pd.DataFrame(data)

In [9]:
print(df)

     Name  Age  Salary
0   Rawal   38   10000
1  Mahesh   21   20000
2  Yogita   11   30000
3  Dhawal   20   40000

In [10]:
print(type(df))

<class 'pandas.DataFrame'>

In [11]:
#2 Basic DataFrame understanding

In [ ]:
df.head()  #top rows

     Name  Age  Salary
0   Rawal   38   10000
1  Mahesh   21   20000
2  Yogita   11   30000
3  Dhawal   20   40000

In [13]:
df.head(2)  #top 2 row

     Name  Age  Salary
0   Rawal   38   10000
1  Mahesh   21   20000

In [14]:
df.tail() #bottom Rows

     Name  Age  Salary
0   Rawal   38   10000
1  Mahesh   21   20000
2  Yogita   11   30000
3  Dhawal   20   40000

In [15]:
df.tail(2)  #bottom row

     Name  Age  Salary
2  Yogita   11   30000
3  Dhawal   20   40000

In [ ]:
df.shape #how many rows and columns

(4, 3)

In [ ]:
df.columns #columns name

Index(['Name', 'Age', 'Salary'], dtype='str')

In [22]:
df.rename(columns={'Salary' : 'Monthly_Salary'}, inplace=True) #rename column name

In [23]:
df

     Name  Age  Monthly_Salary
0   Rawal   38           10000
1  Mahesh   21           20000
2  Yogita   11           30000
3  Dhawal   20           40000

In [ ]:
df.info() #information about data

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      str
 1   Age             4 non-null      int64
 2   Monthly_Salary  4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [26]:
df.describe() #statistical information about data

             Age  Monthly_Salary
count   4.000000        4.000000
mean   22.500000    25000.000000
std    11.269428    12909.944487
min    11.000000    10000.000000
25%    17.750000    17500.000000
50%    20.500000    25000.000000
75%    25.250000    32500.000000
max    38.000000    40000.000000

In [27]:
#3 Save and Load Data from csv file

In [ ]:
df.to_csv('Test_data.csv', index=False) #(Exportdata frame) save data to csv file

In [38]:
load_df = pd.read_csv("Test_data.csv") 
#(Import data frame) Load data from csv file
load_df

     Name  Age  Monthly_Salary
0   Rawal   38           15000
1  Mahesh   21           20000
2  Yogita   11           30000
3  Dhawal   20           40000

In [39]:
#4 Rows & Columns - selection

In [ ]:
#select all columns
df

     Name  Age  Monthly_Salary
0   Rawal   38           15000
1  Mahesh   21           20000
2  Yogita   11           30000
3  Dhawal   20           40000

In [ ]:
#select single columns

In [42]:
df[['Name']]

     Name
0   Rawal
1  Mahesh
2  Yogita
3  Dhawal

In [43]:
#select multiple columns
df[['Name','Age']]

     Name  Age
0   Rawal   38
1  Mahesh   21
2  Yogita   11
3  Dhawal   20

In [ ]:
#select rows
#loc - Label name based selection
df.loc[df.Name == 'Mahesh']
df.loc[(df.Name == 'Mahesh') & (df.Monthly_Salary > 10000)]

     Name  Age  Monthly_Salary
1  Mahesh   21           20000

In [49]:
#select rows by index position
df.loc[0:2] #0 to 2 rows index position

     Name  Age  Monthly_Salary
0   Rawal   38           15000
1  Mahesh   21           20000
2  Yogita   11           30000

In [ ]:
#iloc - index - value based selection
# df.iloc[0]  #0 is index value of row

#[start:stop:step] 
df.iloc[0:2]  #0 to 2 rows where 0 is starting index and print 2 rows excluding 2nd index value

     Name  Age  Monthly_Salary
0   Rawal   38           15000
1  Mahesh   21           20000

In [ ]:
 #5 Filter dataframe

In [51]:
df

     Name  Age  Monthly_Salary
0   Rawal   38           15000
1  Mahesh   21           20000
2  Yogita   11           30000
3  Dhawal   20           40000

In [ ]:
df['Age'] >= 18  #retuns boolean value true or False

0     True
1     True
2    False
3     True
Name: Age, dtype: bool

In [ ]:
df[df['Age'] >= 18] #returns rows where Age is greater than or equal to 18

     Name  Age  Monthly_Salary
0   Rawal   38           15000
1  Mahesh   21           20000
3  Dhawal   20           40000

In [60]:
df_age_filter = df[df['Age'] >= 18] #create new variable and store filtered data in it
df_age_filter

     Name  Age  Monthly_Salary
0   Rawal   38           15000
1  Mahesh   21           20000
3  Dhawal   20           40000

In [66]:
df[(df['Age'] >= 18) & (df['Monthly_Salary'] >= 25000)] #returns rows where age is greater than 18 and monthly salary is greater than 25000

     Name  Age  Monthly_Salary
3  Dhawal   20           40000

In [67]:
df.where(df['Age'] >= 18) #returns rows where age is greater than 18 and other rows will be NaN

     Name   Age  Monthly_Salary
0   Rawal  38.0         15000.0
1  Mahesh  21.0         20000.0
2     NaN   NaN             NaN
3  Dhawal  20.0         40000.0

In [68]:
df.where(df['Age'] >= 18, other='Not Eligible') #returns rows where age is greater than 18 and other rows will be 'Not Eligible'

           Name           Age Monthly_Salary
0         Rawal            38          15000
1        Mahesh            21          20000
2  Not Eligible  Not Eligible   Not Eligible
3        Dhawal            20          40000

In [69]:
#6 Rows and columns - operations (Add, update, Delete)

In [70]:
df

     Name  Age  Monthly_Salary
0   Rawal   38           15000
1  Mahesh   21           20000
2  Yogita   11           30000
3  Dhawal   20           40000

In [71]:
#add new column
df['Team'] = ['DA','HR','Student','CEO']
df

     Name  Age  Monthly_Salary     Team
0   Rawal   38           15000       DA
1  Mahesh   21           20000       HR
2  Yogita   11           30000  Student
3  Dhawal   20           40000      CEO

In [ ]:
#Perform operation on column and create a new column
df['Bonus'] = df['Monthly_Salary'] * 0.2
df

     Name  Age  Monthly_Salary     Team   Bonus
0   Rawal   38           15000       DA  3000.0
1  Mahesh   21           20000       HR  4000.0
2  Yogita   11           30000  Student  6000.0
3  Dhawal   20           40000      CEO  8000.0

In [76]:
#Add New row 
df.loc[len(df)] = ['Sheetal',19,35300,'Freelancer',6420]
df

      Name  Age  Monthly_Salary        Team   Bonus
0    Rawal   38           15000          DA  3000.0
1   Mahesh   21           20000          HR  4000.0
2   Yogita   11           30000     Student  6000.0
3   Dhawal   20           40000         CEO  8000.0
4  Sheetal   19           35300  Freelancer  6420.0

In [88]:
#update existing row - using index name 
df.loc[2,'Monthly_Salary'] = 1000
df

      Name  Age  Monthly_Salary        Team   Bonus
0    Rawal   38           15000          DA  3000.0
1   Mahesh   21           20000          HR  4000.0
2   Yogita   11            1000     Student  6000.0
3   Dhawal   20           40000         CEO  8000.0
4  Sheetal   19           35300  Freelancer  6420.0

In [90]:
#update exisiting row - using index position
df.loc[df.Name == 'Mahesh','Monthly_Salary'] = 35500
df

      Name  Age  Monthly_Salary        Team   Bonus
0    Rawal   38           15000          DA  3000.0
1   Mahesh   21           35500          HR  4000.0
2   Yogita   11            1000     Student  6000.0
3   Dhawal   20           40000         CEO  8000.0
4  Sheetal   19           35300  Freelancer  6420.0

In [ ]:
# Delete value - row and column values

#df.drop('Bonus',axis=1,inplace=True) - delete column

#delete row
df = df.drop(df[df.Name == 'Sheetal'].index)
df



# Note
# df = df.drop() and inline inplace=True is same

     Name  Age  Monthly_Salary     Team
0   Rawal   38           15000       DA
1  Mahesh   21           35500       HR
2  Yogita   11            1000  Student
3  Dhawal   20           40000      CEO

In [99]:
#df.drop(['Bonus','Team'], axis=1) # delete multiple columns

In [100]:
#rename
df.rename(columns={'Monthly_Salary' : 'Salary'}, inplace=True)

In [102]:
#Sort Value
#df.sort_values('Salary')  - Ascending Order by default
df.sort_values('Salary', ascending=False)

     Name  Age  Salary     Team
3  Dhawal   20   40000      CEO
1  Mahesh   21   35500       HR
0   Rawal   38   15000       DA
2  Yogita   11    1000  Student

In [103]:
#7 Working with date value/datatype

In [104]:
df['DOJ'] = ['2024-05-01','2024-02-15','2024-08-01','2024-01-01']
df

     Name  Age  Salary     Team         DOJ
0   Rawal   38   15000       DA  2024-05-01
1  Mahesh   21   35500       HR  2024-02-15
2  Yogita   11    1000  Student  2024-08-01
3  Dhawal   20   40000      CEO  2024-01-01

In [105]:
df['DOJ'].dtype

In [106]:
df['DOJ'] = pd.to_datetime(df['DOJ'])

In [107]:
df['DOJ'].dtype

dtype('<M8[us]')

In [109]:
df1

     Name  Age  Salary     Team        DOJ
0   Rawal   38   15000       DA 2024-05-01
1  Mahesh   21   35500       HR 2024-02-15
2  Yogita   11    1000  Student 2024-08-01
3  Dhawal   20   40000      CEO 2024-01-01

In [110]:
df

     Name  Age  Salary     Team        DOJ
0   Rawal   38   15000       DA 2024-05-01
1  Mahesh   21   35500       HR 2024-02-15
2  Yogita   11    1000  Student 2024-08-01
3  Dhawal   20   40000      CEO 2024-01-01

In [ ]:
# Extract year, month, week, day

# df['DOJ'].dt.year
# df['DOJ'].dt.month
# df['DOJ'].dt.day
df['DOJ'].dt.day_name()

0    Wednesday
1     Thursday
2     Thursday
3       Monday
Name: DOJ, dtype: str

In [118]:
df['Month'] = df['DOJ'].dt.month
df

     Name  Age  Salary     Team        DOJ  Month
0   Rawal   38   15000       DA 2024-05-01      5
1  Mahesh   21   35500       HR 2024-02-15      2
2  Yogita   11    1000  Student 2024-08-01      8
3  Dhawal   20   40000      CEO 2024-01-01      1

In [122]:
df['DOJ'] + pd.Timedelta(days=90)

0   2024-07-30
1   2024-05-15
2   2024-10-30
3   2024-03-31
Name: DOJ, dtype: datetime64[us]

In [120]:
df

     Name  Age  Salary     Team        DOJ  Month
0   Rawal   38   15000       DA 2024-05-01      5
1  Mahesh   21   35500       HR 2024-02-15      2
2  Yogita   11    1000  Student 2024-08-01      8
3  Dhawal   20   40000      CEO 2024-01-01      1

In [123]:
#8 Handling misiing values
df

     Name  Age  Salary     Team        DOJ  Month
0   Rawal   38   15000       DA 2024-05-01      5
1  Mahesh   21   35500       HR 2024-02-15      2
2  Yogita   11    1000  Student 2024-08-01      8
3  Dhawal   20   40000      CEO 2024-01-01      1

In [124]:
df.isnull()

    Name    Age  Salary   Team    DOJ  Month
0  False  False   False  False  False  False
1  False  False   False  False  False  False
2  False  False   False  False  False  False
3  False  False   False  False  False  False

In [129]:
import numpy as np

In [131]:
df.loc[df.Name=='Yogita', 'Salary'] = np.nan
df

     Name  Age   Salary     Team        DOJ  Month
0   Rawal   38  15000.0       DA 2024-05-01      5
1  Mahesh   21  35500.0       HR 2024-02-15      2
2  Yogita   11      NaN  Student 2024-08-01      8
3  Dhawal   20  40000.0      CEO 2024-01-01      1

In [132]:
df.isnull()

    Name    Age  Salary   Team    DOJ  Month
0  False  False   False  False  False  False
1  False  False   False  False  False  False
2  False  False    True  False  False  False
3  False  False   False  False  False  False

In [133]:
df.isnull().sum()

Name      0
Age       0
Salary    1
Team      0
DOJ       0
Month     0
dtype: int64

In [134]:
df.fillna(0)

     Name  Age   Salary     Team        DOJ  Month
0   Rawal   38  15000.0       DA 2024-05-01      5
1  Mahesh   21  35500.0       HR 2024-02-15      2
2  Yogita   11      0.0  Student 2024-08-01      8
3  Dhawal   20  40000.0      CEO 2024-01-01      1

In [135]:
df

     Name  Age   Salary     Team        DOJ  Month
0   Rawal   38  15000.0       DA 2024-05-01      5
1  Mahesh   21  35500.0       HR 2024-02-15      2
2  Yogita   11      NaN  Student 2024-08-01      8
3  Dhawal   20  40000.0      CEO 2024-01-01      1

In [136]:
# 9 Aggregation and Group by

In [ ]:
df['Month'].value_counts() #frequence of value

Month
5    1
2    1
8    1
1    1
Name: count, dtype: int64

In [139]:
df[df['Month']==1].value_counts()

Name    Age  Salary   Team  DOJ         Month
Dhawal  20   40000.0  CEO   2024-01-01  1        1
Name: count, dtype: int64

In [ ]:
#Aggregation based on group by
df.groupby('Month')['Salary'].sum()

Month
1    40000.0
2    35500.0
5    15000.0
8        0.0
Name: Salary, dtype: float64

In [144]:
df.groupby('Month').aggregate({'Salary': 'mean','Name':'count'})

        Salary  Name
Month
1      40000.0     1
2      35500.0     1
5      15000.0     1
8          NaN     1

In [145]:
#10 Concatenate and merge Dataframe (JOINS)
df

     Name  Age   Salary     Team        DOJ  Month
0   Rawal   38  15000.0       DA 2024-05-01      5
1  Mahesh   21  35500.0       HR 2024-02-15      2
2  Yogita   11      NaN  Student 2024-08-01      8
3  Dhawal   20  40000.0      CEO 2024-01-01      1

In [147]:
df1 = pd.DataFrame({'ID':[1,2,2,3],'Score':[88,96,77,79]})
df1

   ID  Score
0   1     88
1   2     96
2   2     77
3   3     79

In [149]:
df2 = pd.DataFrame({'ID':[1,2,3],'Name':['A','B','C']})
df2

   ID Name
0   1    A
1   2    B
2   3    C

In [151]:
#Vertical / row level / top on top
pd.concat([df1,df2],axis=0)

   ID  Score Name
0   1   88.0  NaN
1   2   96.0  NaN
2   2   77.0  NaN
3   3   79.0  NaN
0   1    NaN    A
1   2    NaN    B
2   3    NaN    C

In [ ]:
#Horizontal / row level / top on top
pd.concat([df1,df2],axis=1)

   ID  Score   ID Name
0   1     88  1.0    A
1   2     96  2.0    B
2   2     77  3.0    C
3   3     79  NaN  NaN

In [158]:
#merge = Join
pd.merge(df1,df2, how='inner',on='ID')

   ID  Score Name
0   1     88    A
1   2     96    B
2   2     77    B
3   3     79    C

In [159]:
pd.merge(df1, df2, how='inner',left_on='ID', right_on='ID')

   ID  Score Name
0   1     88    A
1   2     96    B
2   2     77    B
3   3     79    C

In [160]:
# 11 AI and ChatGPT
df

     Name  Age   Salary     Team        DOJ  Month
0   Rawal   38  15000.0       DA 2024-05-01      5
1  Mahesh   21  35500.0       HR 2024-02-15      2
2  Yogita   11      NaN  Student 2024-08-01      8
3  Dhawal   20  40000.0      CEO 2024-01-01      1

In [163]:
df[(df['Salary'] >= 35000) & (df['Age'] >= 18)]

     Name  Age   Salary Team        DOJ  Month
1  Mahesh   21  35500.0   HR 2024-02-15      2
3  Dhawal   20  40000.0  CEO 2024-01-01      1

In [164]:
df[(df['Age'] >= 15) & (df['Salary'] >= 11200)]

     Name  Age   Salary Team        DOJ  Month
0   Rawal   38  15000.0   DA 2024-05-01      5
1  Mahesh   21  35500.0   HR 2024-02-15      2
3  Dhawal   20  40000.0  CEO 2024-01-01      1

In [165]:
df.query("Month == 1 and Salary > 35000")

     Name  Age   Salary Team        DOJ  Month
3  Dhawal   20  40000.0  CEO 2024-01-01      1

In [166]:
df.query("Age >= 18")

     Name  Age   Salary Team        DOJ  Month
0   Rawal   38  15000.0   DA 2024-05-01      5
1  Mahesh   21  35500.0   HR 2024-02-15      2
3  Dhawal   20  40000.0  CEO 2024-01-01      1

In [167]:
df.query("Age > 15 or Salary >= 35000")

     Name  Age   Salary Team        DOJ  Month
0   Rawal   38  15000.0   DA 2024-05-01      5
1  Mahesh   21  35500.0   HR 2024-02-15      2
3  Dhawal   20  40000.0  CEO 2024-01-01      1

In [ ]:
### Work : Create a dataframe to practice pivot table in pandas

In [1]:
import pandas as pd

data = {
    "Order_ID": range(1, 21),
    "Date": [
        "2026-01-05", "2026-01-08", "2026-01-12", "2026-01-15",
        "2026-02-03", "2026-02-07", "2026-02-11", "2026-02-18",
        "2026-03-02", "2026-03-06", "2026-03-10", "2026-03-15",
        "2026-04-04", "2026-04-09", "2026-04-14", "2026-04-20",
        "2026-05-03", "2026-05-08", "2026-05-16", "2026-05-22"
    ],
    "Region": [
        "West", "North", "South", "West",
        "North", "South", "East", "West",
        "East", "North", "South", "West",
        "North", "East", "South", "West",
        "East", "North", "South", "West"
    ],
    "Category": [
        "Electronics", "Furniture", "Electronics", "Clothing",
        "Furniture", "Clothing", "Electronics", "Furniture",
        "Clothing", "Electronics", "Furniture", "Clothing",
        "Electronics", "Furniture", "Clothing", "Electronics",
        "Furniture", "Clothing", "Electronics", "Furniture"
    ],
    "Product": [
        "Laptop", "Chair", "Mobile", "T-Shirt",
        "Table", "Jeans", "Headphones", "Desk",
        "Jacket", "Tablet", "Sofa", "Shoes",
        "Monitor", "Bookshelf", "Jeans", "Keyboard",
        "Chair", "T-Shirt", "Mobile", "Desk"
    ],
    "Salesperson": [
        "Rahul", "Priya", "Amit", "Neha",
        "Rahul", "Amit", "Priya", "Neha",
        "Rahul", "Priya", "Amit", "Neha",
        "Rahul", "Priya", "Amit", "Neha",
        "Rahul", "Amit", "Priya", "Neha"
    ],
    "Quantity": [
        2, 5, 3, 8, 4, 6, 5, 2, 7, 3,
        2, 9, 4, 3, 5, 6, 7, 10, 4, 2
    ],
    "Sales": [
        120000, 25000, 75000, 12000,
        40000, 18000, 15000, 30000, 21000, 90000,
        55000, 27000, 60000, 22000, 15000, 18000,
        35000, 15000, 100000, 30000
    ],
    "Profit": [
        18000, 5000, 12000, 3000,
        7000, 4000, 3000, 6000, 5000, 15000,
        9000, 6000, 10000, 4000, 3000, 3500,
        7000, 3000, 16000, 6000
    ]
}

df = pd.DataFrame(data)

df["Date"] = pd.to_datetime(df["Date"])

df

,Order_ID,Date,Region,Category,Product,Salesperson,Quantity,Sales,Profit
0,1,2026-01-05,West,Electronics,Laptop,Rahul,2,120000,18000
1,2,2026-01-08,North,Furniture,Chair,Priya,5,25000,5000
2,3,2026-01-12,South,Electronics,Mobile,Amit,3,75000,12000
3,4,2026-01-15,West,Clothing,T-Shirt,Neha,8,12000,3000
4,5,2026-02-03,North,Furniture,Table,Rahul,4,40000,7000
5,6,2026-02-07,South,Clothing,Jeans,Amit,6,18000,4000
6,7,2026-02-11,East,Electronics,Headphones,Priya,5,15000,3000
7,8,2026-02-18,West,Furniture,Desk,Neha,2,30000,6000
8,9,2026-03-02,East,Clothing,Jacket,Rahul,7,21000,5000
9,10,2026-03-06,North,Electronics,Tablet,Priya,3,90000,15000
10,11,2026-03-10,South,Furniture,Sofa,Amit,2,55000,9000
11,12,2026-03-15,West,Clothing,Shoes,Neha,9,27000,6000
12,13,2026-04-04,North,Electronics,Monitor,Rahul,4,60000,10000
13,14,2026-04-09,East,Furniture,Bookshelf,Priya,3,22000,4000
14,15,2026-04-14,South,Clothing,Jeans,Amit,5,15000,3000
15,16,2026-04-20,West,Electronics,Keyboard,Neha,6,18000,3500
16,17,2026-05-03,East,Furniture,Chair,Rahul,7,35000,7000
17,18,2026-05-08,North,Clothing,T-Shirt,Amit,10,15000,3000
18,19,2026-05-16,South,Electronics,Mobile,Priya,4,100000,16000
19,20,2026-05-22,West,Furniture,Desk,Neha,2,30000,6000

In [11]:
pd.pivot_table(
    df,
    values="Sales",
    index="Salesperson",
    columns="Category",
    aggfunc="sum"
)

Category     Clothing  Electronics  Furniture
Salesperson
Amit          48000.0      75000.0    55000.0
Neha          39000.0      18000.0    60000.0
Priya             NaN     205000.0    47000.0
Rahul         21000.0     180000.0    75000.0

In [7]:
pd.pivot_table(
    df,
    values=["Profit","Sales"],
    index="Category",
    aggfunc="sum"
)

             Profit   Sales
Category
Clothing      24000  108000
Electronics   77500  478000
Furniture     44000  237000

In [2]:
pd.pivot_table(
    df,
    values="Sales",
    index="Region",
    aggfunc="sum"
)

         Sales
Region
East     93000
North   230000
South   263000
West    237000

In [3]:
pd.pivot_table(
    df,
    values="Sales",
    index="Category",
    aggfunc="sum"
)

              Sales
Category
Clothing     108000
Electronics  478000
Furniture    237000

In [4]:
pd.pivot_table(
    df,
    values="Sales",
    index="Region",
    columns="Category",
    aggfunc="sum"
)

Category  Clothing  Electronics  Furniture
Region
East         21000        15000      57000
North        15000       150000      65000
South        33000       175000      55000
West         39000       138000      60000

In [5]:
pd.pivot_table(
    df,
    values=["Sales", "Profit"],
    index="Region",
    aggfunc="sum"
)

        Profit   Sales
Region
East     19000   93000
North    40000  230000
South    44000  263000
West     42500  237000

In [ ]:
#Practice_With_Dhawal